apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
    name: k0s-cluster
    user: admin
spec:
    k0s:
      config:
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: ClusterConfig
        metadata:
          name: k0s
          namespace: kube-system
        spec:
          api:
            address: 10.0.1.10
            k0sApiPort: 9443
            port: 6443
            sans:
            - 10.0.1.10
            - fe80::8ff:c5ff:fe9c:951
          controllerManager: {}
          extensions:
            helm:
              concurrencyLevel: 5
          installConfig:
            users:
              etcdUser: etcd
              kineUser: kube-apiserver
              konnectivityUser: konnectivity-server
              kubeAPIserverUser: kube-apiserver
              kubeSchedulerUser: kube-scheduler
          konnectivity:
            adminPort: 8133
            agentPort: 8132
          network:
            clusterDomain: cluster.local
            dualStack:
              enabled: false
            kubeProxy:
              iptables:
                minSyncPeriod: 0s
                syncPeriod: 0s
              ipvs:
                minSyncPeriod: 0s
                syncPeriod: 0s
                tcpFinTimeout: 0s
                tcpTimeout: 0s
                udpTimeout: 0s
              metricsBindAddress: 0.0.0.0:10249
              mode: iptables
              nftables:
                minSyncPeriod: 0s
                syncPeriod: 0s
            nodeLocalLoadBalancing:
              enabled: false
              envoyProxy:
                apiServerBindPort: 7443
                konnectivityServerBindPort: 7132
              type: EnvoyProxy
            podCIDR: 10.244.0.0/16
            provider: calico
            serviceCIDR: 10.96.0.0/12
          scheduler: {}
          storage:
            etcd:
              peerAddress: 10.0.1.10
            type: etcd
          telemetry:
            enabled: true

    hosts:
    - ssh:
        address: 10.0.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller

    - ssh:
        address: 10.1.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker

    - ssh:
        address: 10.2.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker


    - ssh:
        address: 10.3.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker