apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
    name: k0s-cluster
    user: admin
spec:
    k0s:
      config:
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: ClusterConfig
        metadata:
          name: k0s
          namespace: kube-system
        spec:
          extensions:
            helm:
              concurrencyLevel: 5
              repositories:
              - name: aws-cloud-controller-manager
                url: https://kubernetes.github.io/cloud-provider-aws
              charts:
              - name: aws-cloud-controller-manager
                chartname: aws-cloud-controller-manager/aws-cloud-controller-manager
                version: 0.0.8
                timeout: 10m
                order: 1
                namespace: kube-system
                values: |
                  args:
                    - --v=2
                    - --cloud-provider=aws
                    - --configure-cloud-routes=false
                  nodeSelector:
                    kubernetes.io/os: linux
                    node-role.kubernetes.io/control-plane: null
          network:
            clusterDomain: cluster.local
            dualStack:
              enabled: false
            kubeProxy:
              iptables:
                minSyncPeriod: 0s
                syncPeriod: 0s
              ipvs:
                minSyncPeriod: 0s
                syncPeriod: 0s
                tcpFinTimeout: 0s
                tcpTimeout: 0s
                udpTimeout: 0s
              metricsBindAddress: 0.0.0.0:10249
              mode: iptables
              nftables:
                minSyncPeriod: 0s
                syncPeriod: 0s
            nodeLocalLoadBalancing:
              enabled: false
              envoyProxy:
                apiServerBindPort: 7443
                konnectivityServerBindPort: 7132
              type: EnvoyProxy
            podCIDR: 10.244.0.0/16
            provider: calico
            serviceCIDR: 10.96.0.0/12
          scheduler: {}
          storage:
            etcd:
              peerAddress: 10.0.1.10
            type: etcd
          telemetry:
            enabled: true
    hosts:
    - ssh:
        address: 10.0.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller

    - ssh:
        address: 10.1.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
      installFlags:
        - --enable-cloud-provider
        - --kubelet-extra-args=--cloud-provider=external

    - ssh:
        address: 10.2.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
      installFlags:
        - --enable-cloud-provider
        - --kubelet-extra-args=--cloud-provider=external

    - ssh:
        address: 10.3.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
      installFlags:
        - --enable-cloud-provider
        - --kubelet-extra-args=--cloud-provider=external

    - ssh:
        address: 10.4.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
      installFlags:
        - --enable-cloud-provider
        - --kubelet-extra-args=--cloud-provider=external