
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
    name: k0s-cluster
    user: admin
spec:
    k0s:
      version: 0.10.0
      config:
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: ClusterConfig
        metadata:
          name: my-k0s-cluster
        spec:
          images:
            calico:
              cni:
                image: calico/cni
                version: v3.16.2
    hosts:
    - ssh:
        address: 10.0.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller

    - ssh:
        address: 10.1.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker

    - ssh:
        address: 10.2.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker


    - ssh:
        address: 10.3.1.10
        user: ec2-user
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker